CREATE DATABASE calendar;

CREATE USER 'Admin'@'localhost' IDENTIFIED WITH mysql_native_password;
GRANT ALL PRIVILEGES ON *.* TO 'Admin'@'localhost' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
SET PASSWORD FOR 'Admin'@'localhost' = '***';
GRANT ALL PRIVILEGES ON `calendar`.* TO 'Admin'@'localhost';